name: Hotfix reminder

on:
  push:
    branches: [ stable ]

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'develop'

      # Only open issue if branches are not even
      - name: Diff develop and stable branch
        id: diff
        run: |
          git fetch
          git checkout stable
          if [ "$(git rev-parse stable)" = "$(git rev-parse develop)" ]; then
            echo "::set-output name=even::true"
          else
            echo "::set-output name=even::false"
          fi
          
      - name: Open issue
        if: ${{ steps.diff.outputs.even != true }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Hotfix review',
              body: `Stable branch has been hotfixed. Needs review before next update. ${context.payload.head_commit.url}`,
              labels: ['hotfix']
            })
